const BLACK_CARDS = [
  // ── Base Pack ─────────────────────────────────────────────────────────────────
  { text: "Achievement unlocked: ___.", pick: 1, pack: "Nerd" },
  { text: "And in the end, the dragon was not evil; he just wanted ___.", pick: 1, pack: "Nerd" },
  { text: "Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?", pick: 1, pack: "Nerd" },
  { text: "Critics are raving about HBO's new Game of Thrones spin-off, \"___ of ___\".", pick: 2, pack: "Nerd" },
  { text: "Having tired of poetry and music, the immortal elves now fill their days with ___.", pick: 1, pack: "Nerd" },
  { text: "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by ___.", pick: 1, pack: "Nerd" },
  { text: "___ is way better in ___ mode.", pick: 2, pack: "Nerd" },
  { text: "Madam President, the asteroid is headed directly for Earth and there's only one thing that can stop it: ___.", pick: 2, pack: "Nerd" },
  { text: "What is the answer to life, the universe, and everything?", pick: 1, pack: "Nerd" },
  { text: "You're not going to believe this, but I'm you from the future! You've got to stop ___.", pick: 1, pack: "Nerd" },
  { text: "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: ___.", pick: 1, pack: "Nerd" },
  { text: "(Heavy breathing) Luke, I am ___.", pick: 1, pack: "Nerd" },
  { text: "Fear leads to anger. Anger leads to hate. Hate leads to ___.", pick: 1, pack: "Nerd" },
  { text: "You have violated the Prime Directive! You exposed an alien culture to ___ before they were ready.", pick: 1, pack: "Nerd" },
  { text: "Press ↑↑↓↓←→B to unleash ___.", pick: 1, pack: "Nerd" },
  { text: "Computer! Display ___ on screen. Enhance.", pick: 1, pack: "Nerd" },
  { text: "What's the latest bullshit that's troubling this quaint fantasy town?", pick: 1, pack: "Nerd" },
  { text: "This won't be like negotiating with the Vogons. Humans only respond to one thing: ___.", pick: 1, pack: "Nerd" },
  { text: "What made Spock cry?", pick: 1, pack: "Nerd" },

  // ── Dad Pack ──────────────────────────────────────────────────────────────────
  { text: "So apparently Dad was searching Pornhub for \"hot milf ___\".", pick: 1, pack: "Dad Pack" },
  { text: "FW: FW: FW: WARNING!!! VIOLENT GANGS VOREGRUNT CHILDREN!", pick: 1, pack: "Dad Pack" },
  { text: "Whaddya think, money grows on trees? I'm not paying for ___.", pick: 1, pack: "Dad Pack" },
  { text: "Coming up on Turner Classic Movies: Sean Connery and Alec Baldwin star in \"The Hunt for ___\".", pick: 1, pack: "Dad Pack" },
  { text: "Hey, kids. I'm Connor's dad, but you can call me ___.", pick: 1, pack: "Dad Pack" },
  { text: "Young lady, you better knock it off with ___ or you're grounded!", pick: 1, pack: "Dad Pack" },

  // ── Green Box ─────────────────────────────────────────────────────────────────
  { text: "What's about to take this dance floor to the next level?", pick: 1, pack: "Green Box" },
  { text: "I'll take the BBQ bacon burger with a fried egg and fuck it how about ___?", pick: 1, pack: "Green Box" },
  { text: "Well, shit. My eyes ain't so good, but I'll eat my own boot if that ain't ___.", pick: 1, pack: "Green Box" },
  { text: "Feeling so grateful! #amazing #mylife ___.", pick: 1, pack: "Green Box" },
  { text: "No, no, no, no. I will NOT let ___ ruin this wedding.", pick: 1, pack: "Green Box" },
  { text: "I don't believe in God. I believe in ___.", pick: 1, pack: "Green Box" },
  { text: "This Friday at the Liquid Lounge, it's ___ Night! Ladies drink free.", pick: 1, pack: "Green Box" },
  { text: "She's just one of the guys, you know? She likes beer, and football, and ___.", pick: 1, pack: "Green Box" },
  { text: "Girls just wanna have ___.", pick: 1, pack: "Green Box" },
  { text: "She's a lady in the streets, ___ in the sheets.", pick: 1, pack: "Green Box" },
  { text: "Coming to Red Lobster® this month, ___.", pick: 1, pack: "Green Box" },
  { text: "Google Calendar alert: ___ in 10 minutes.", pick: 1, pack: "Green Box" },
  { text: "LSD + ___ = really bad time.", pick: 1, pack: "Green Box" },
  { text: "I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like ___.", pick: 1, pack: "Green Box" },
  { text: "What sucks balls?", pick: 1, pack: "Green Box" },
  { text: "Brought to you by ___.", pick: 2, pack: "Green Box" },
  { text: "Most Americans would not vote for a candidate who is openly ___.", pick: 1, pack: "Green Box" },
  { text: "The top Google auto-complete results for \"Barack Obama\": Barack Obama height. Barack Obama net worth. Barack Obama ___.", pick: 1, pack: "Green Box" },
  { text: "If at first you don't succeed, try ___.", pick: 1, pack: "Green Box" },
  { text: "CNN breaking news! Scientists discover ___.", pick: 1, pack: "Green Box" },
  { text: "Best you go back where you came from, now. We don't take too kindly to ___ in these parts.", pick: 1, pack: "Green Box" },
  { text: "I'm sorry, sir, but your insurance plan doesn't cover injuries caused by ___.", pick: 1, pack: "Green Box" },
  { text: "You know who else liked Hitler?", pick: 1, pack: "Green Box" },
  { text: "In the 1950s, psychologists prescribed ___ as a cure for homosexuality.", pick: 1, pack: "Green Box" },
  { text: "I may not be much to look at, but I fuck like ___.", pick: 1, pack: "Green Box" },
  { text: "As Teddy Roosevelt said, \"the four main virtues are honor, temperance, industry, and ___\".", pick: 1, pack: "Green Box" },
  { text: "Mom's to-do list: Buy groceries, Clean up, Soccer practice, ___.", pick: 1, pack: "Green Box" },
  { text: "With a one-time gift of just $10, you can save this child from ___.", pick: 1, pack: "Green Box" },
  { text: "Oh no! Siri, how do I fix ___?", pick: 1, pack: "Green Box" },
  { text: "I've had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw ___.", pick: 1, pack: "Green Box" },
  { text: "Art isn't just a painting in a stuffy museum. Art is alive. Art is ___.", pick: 1, pack: "Green Box" },
  { text: "Errbody in the club ___.", pick: 1, pack: "Green Box" },
  { text: "What totally destroyed my asshole?", pick: 1, pack: "Green Box" },
  { text: "As reparations for slavery, all African Americans will receive ___.", pick: 1, pack: "Green Box" },
  { text: "Ooo, daddy like ___.", pick: 1, pack: "Green Box" },
  { text: "Well if ___ is a crime, then lock me up!", pick: 1, pack: "Green Box" },
  { text: "We do not shake with our left hands in this country. That is the hand we use for ___.", pick: 1, pack: "Green Box" },
  { text: "Poor Brandon, still living in his parents' basement. I heard he never got over ___.", pick: 1, pack: "Green Box" },
  { text: "Run, run, as fast as you can! You can't catch me, I'm ___!", pick: 1, pack: "Green Box" },
  { text: "Dance like there's nobody watching, love like you'll never be hurt, and live like you're ___.", pick: 1, pack: "Green Box" },
  { text: "There is no God. It's just ___ and then you die.", pick: 1, pack: "Green Box" },
  { text: "What are all those whales singing about?", pick: 1, pack: "Green Box" },
  { text: "Son, take it from someone who's been around the block a few times. Nothin' puts her in the mood like ___.", pick: 1, pack: "Green Box" },
  { text: "Summer lovin', had me a blast. ___, happened so fast.", pick: 1, pack: "Green Box" },
  { text: "Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we can offer you ___.", pick: 1, pack: "Green Box" },
  { text: "What will end racism once and for all?", pick: 1, pack: "Green Box" },
  { text: "I've got rhythm, I've got music, I've got ___. Who could ask for anything more?", pick: 1, pack: "Green Box" },
  { text: "Why am I laughing and crying and taking off my clothes?", pick: 1, pack: "Green Box" },
  { text: "What's the most problematic?", pick: 1, pack: "Green Box" },
  { text: "What turned me into a Republican?", pick: 1, pack: "Green Box" },
  { text: "One more thing. Watch out for Big Mike. They say he killed a man with ___.", pick: 1, pack: "Green Box" },
  { text: "You won't believe what's in my pussy. It's ___.", pick: 1, pack: "Green Box" },
  { text: "___ be all like ___.", pick: 2, pack: "Green Box" },
  { text: "Then the princess kissed the frog, and all of a sudden the frog was ___!", pick: 1, pack: "Green Box" },
  { text: "What's the gayest?", pick: 1, pack: "Green Box" },

];
