const BLACK_CARDS = [
  { text: "Achievement unlocked: ___.", pick: 1 },
  { text: "And in the end, the dragon was not evil; he just wanted ___.", pick: 1 },
  { text: "Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?", pick: 1 },
  { text: "Critics are raving about HBO's new Game of Thrones spin-off, \"___ of ___\".", pick: 2 },
  { text: "Having tired of poetry and music, the immortal elves now fill their days with ___.", pick: 1 },
  { text: "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by ___.", pick: 1 },
  { text: "___ is way better in ___ mode.", pick: 2 },
  { text: "Madam President, the asteroid is headed directly for Earth and there's only one thing that can stop it: ___.", pick: 2 },
  { text: "What is the answer to life, the universe, and everything?", pick: 1 },
  { text: "You're not going to believe this, but I'm you from the future! You've got to stop ___.", pick: 1 },
  { text: "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: ___.", pick: 1 },
  { text: "(Heavy breathing) Luke, I am ___.", pick: 1 },
  { text: "Fear leads to anger. Anger leads to hate. Hate leads to ___.", pick: 1 },
  { text: "You have violated the Prime Directive! You exposed an alien culture to ___ before they were ready.", pick: 1 },
  { text: "Press ↑↑↓↓←→B to unleash ___.", pick: 1 },
  { text: "Computer! Display ___ on screen. Enhance.", pick: 1 },
  { text: "What's the latest bullshit that's troubling this quaint fantasy town?", pick: 1 },
  { text: "This won't be like negotiating with the Vogons. Humans only respond to one thing: ___.", pick: 1 },
  { text: "What made Spock cry?", pick: 1 },
];
