const WHITE_CARDS = [
  // ── Base Pack ─────────────────────────────────────────────────────────────────
  { text: "The card Neil Gaiman wrote: \"Three elves at a time.\"", pack: "Nerd" },
  { text: "A weed elemental who gets everyone high.", pack: "Nerd" },
  { text: "Loading from a previous save.", pack: "Nerd" },
  { text: "The collective wail of every Magic player suddenly realizing that they've spent hundreds of dollars on pieces of cardboard.", pack: "Nerd" },
  { text: "Ser Jorah Mormont's cerulean-blue balls.", pack: "Nerd" },
  { text: "True love's kiss.", pack: "Nerd" },
  { text: "Going on an epic adventure and learning a valuable lesson about friendship.", pack: "Nerd" },
  { text: "Kneeing a wizard in the balls.", pack: "Nerd" },
  { text: "Bathing naked in a moonlit grove.", pack: "Nerd" },
  { text: "A ghoul.", pack: "Nerd" },
  { text: "Handcuffing a wizard to a radiator and dousing him with kerosene.", pack: "Nerd" },
  { text: "Offering sexual favors for an ore and a sheep.", pack: "Nerd" },
  { text: "Getting bitten by a radioactive spider and then battling leukemia for 30 years.", pack: "Nerd" },
  { text: "Freaky, pan-dimensional sex with a demigod.", pack: "Nerd" },
  { text: "Separate drinking fountains for dark elves.", pack: "Nerd" },
  { text: "A homemade, cum-stained Star Trek uniform.", pack: "Nerd" },
  { text: "Make-believe stories for autistic white men.", pack: "Nerd" },
  { text: "Shitting in a wizard's spell book and jizzing in his hat.", pack: "Nerd" },
  { text: "Endless ninjas.", pack: "Nerd" },
  { text: "How hot Orlando Bloom was in Lord of the Rings.", pack: "Nerd" },
  { text: "Getting bitch slapped by Dhalsim.", pack: "Nerd" },
  { text: "A mysterious, floating orb.", pack: "Nerd" },
  { text: "A fully-dressed female videogame character.", pack: "Nerd" },
  { text: "Gender equality.", pack: "Nerd" },
  { text: "Stuffing my balls into a Sega Genesis and pressing the power button.", pack: "Nerd" },
  { text: "Running out of stamina.", pack: "Nerd" },
  { text: "Yoshi's huge egg-laying cloaca.", pack: "Nerd" },
  { text: "The Cock Ring of Alacrity.", pack: "Nerd" },
  { text: "Charging up all the way.", pack: "Nerd" },
  { text: "The depression that ensues after catching 'em all.", pack: "Nerd" },
  { text: "Accidentally conjuring a legless horse that can't stop ejaculating.", pack: "Nerd" },
  { text: "Forgetting to eat, and consequently dying.", pack: "Nerd" },
  { text: "A grumpy old Harrison Ford who'd rather be doing anything else.", pack: "Nerd" },
  { text: "Sharpening a foam broadsword on a foam whetstone.", pack: "Nerd" },
  { text: "Eating a pizza that's lying in the street to gain health.", pack: "Nerd" },
  { text: "Eternal darkness.", pack: "Nerd" },
  { text: "Reading The Hobbit under the covers while mom and dad scream at each other downstairs.", pack: "Nerd" },
  { text: "Hodor.", pack: "Nerd" },
  { text: "Shooting a wizard with a gun.", pack: "Nerd" },
  { text: "Taking 2d6 emotional damage.", pack: "Nerd" },
  { text: "A CGI dragon.", pack: "Nerd" },
  { text: "The all-seeing Eye of Sauron.", pack: "Nerd" },
  { text: "Achieving 500 actions per minute.", pack: "Nerd" },
  { text: "A magical kingdom with dragons and elves and no black people.", pack: "Nerd" },
  { text: "Beep beep boop beep boop.", pack: "Nerd" },
  { text: "Dinosaurs who wear armor and you ride them and they kick ass.", pack: "Nerd" },
  { text: "KHAAAAAAAAAAN!", pack: "Nerd" },
  { text: "Tapping Serra Angel.", pack: "Nerd" },
  { text: "How great of a movie Men in Black was.", pack: "Nerd" },
  { text: "A dwarf who won't leave you alone until you compare penis sizes.", pack: "Nerd" },
  { text: "A Hitachi Magic Wand.", pack: "Nerd" },
  { text: "A gay sorcerer who turns everyone gay.", pack: "Nerd" },
  { text: "Nine seasons of sexual tension with David Duchovny.", pack: "Nerd" },
  { text: "Masturbating Yoda's leathery turtle-penis.", pack: "Nerd" },
  { text: "A misty room full of glistening egg sacs.", pack: "Nerd" },
  { text: "Frantically writing equations on a chalkboard.", pack: "Nerd" },
  { text: "Darmok and Jalad at Tanagra.", pack: "Nerd" },
  { text: "A protagonist with no qualities.", pack: "Nerd" },
  { text: "Going too far with science and bad things happening.", pack: "Nerd" },
  { text: "Vulcan sex-madness.", pack: "Nerd" },
  { text: "That girl from the Hunger Games.", pack: "Nerd" },
  { text: "Cheerful blowjob robots.", pack: "Nerd" },
  { text: "Three boobs.", pack: "Nerd" },
  { text: "Funkified aliens from the planet Groovius.", pack: "Nerd" },
  { text: "The ending of Lost.", pack: "Nerd" },
  { text: "Cosmic bowling.", pack: "Nerd" },
  { text: "An alternate history where Hitler was gay but he still killed all those people.", pack: "Nerd" },
  { text: "The dystopia we're living in right now.", pack: "Nerd" },
  { text: "A planet-devouring space worm named Rachel.", pack: "Nerd" },
  { text: "Trimming the poop out of Chewbacca's butt hair.", pack: "Nerd" },
  { text: "A hazmat suit full of farts.", pack: "Nerd" },
  { text: "Laying thousands of eggs in a man's colon.", pack: "Nerd" },

  // ── Dad Pack ──────────────────────────────────────────────────────────────────
  { text: "Puns.", pack: "Dad Pack" },
  { text: "Coaching the 7th grade girls basketball team.", pack: "Dad Pack" },
  { text: "Standing in the living room holding two remote controls.", pack: "Dad Pack" },
  { text: "Kidnapping Liam Neeson's daughter.", pack: "Dad Pack" },
  { text: "Divorce.", pack: "Dad Pack" },
  { text: "Forty-two years of repressed homosexuality.", pack: "Dad Pack" },
  { text: "Dad's famous chili.", pack: "Dad Pack" },
  { text: "Finding a place to sit down.", pack: "Dad Pack" },
  { text: "Flirting with the ladies at the bank.", pack: "Dad Pack" },
  { text: "Dolby Digital Surround Sound.", pack: "Dad Pack" },
  { text: "The son of a bitch who knocked up my daughter.", pack: "Dad Pack" },
  { text: "What Dad has to say about Muslims.", pack: "Dad Pack" },
  { text: "Going bald.", pack: "Dad Pack" },
  { text: "Dad's big sex night.", pack: "Dad Pack" },
  { text: "The nipples of a man.", pack: "Dad Pack" },
  { text: "Emotional unavailability.", pack: "Dad Pack" },
  { text: "A positive male role model.", pack: "Dad Pack" },
  { text: "Stealing a child's innocence and keeping it forever.", pack: "Dad Pack" },
  { text: "Having a heart attack.", pack: "Dad Pack" },
  { text: "Sitting on the toilet for 45 minutes.", pack: "Dad Pack" },
  { text: "Tripping on an object and becoming angry.", pack: "Dad Pack" },
  { text: "Making the printer work.", pack: "Dad Pack" },
  { text: "Having a bunch of kids by accident.", pack: "Dad Pack" },
  { text: "Dad coming home drunk.", pack: "Dad Pack" },

  // ── Green Box ─────────────────────────────────────────────────────────────────
  { text: "Math.", pack: "Green Box" },
  { text: "Watching you die.", pack: "Green Box" },
  { text: "An arrangement wherein I give a person money and they have sex with me.", pack: "Green Box" },
  { text: "Tiny rancid girl farts.", pack: "Green Box" },
  { text: "Having sex with a man and then eating his head.", pack: "Green Box" },

  // ── Green Box (white) ─────────────────────────────────────────────────────────
  { text: "The wind.", pack: "Green Box" },
  { text: "Twisting my cock and balls into a balloon poodle.", pack: "Green Box" },
  { text: "Just now finding out about the Armenian Genocide.", pack: "Green Box" },
  { text: "Gayle from HR.", pack: "Green Box" },
  { text: "Jason, the teen mayor.", pack: "Green Box" },
  { text: "Esmeralda, my most beautiful daughter.", pack: "Green Box" },
  { text: "Loud, scary thunder.", pack: "Green Box" },
  { text: "A gun that shoots cobras.", pack: "Green Box" },
  { text: "Opening your mouth to talk and a big penis flops out.", pack: "Green Box" },
  { text: "Gary.", pack: "Green Box" },
  { text: "That bitch, Stacy.", pack: "Green Box" },
  { text: "Trevor, the world's greatest boyfriend.", pack: "Green Box" },
  { text: "Eating ass.", pack: "Green Box" },
  { text: "Bad emotions I don't want.", pack: "Green Box" },
  { text: "Out-of-control teenage blowjob parties.", pack: "Green Box" },
  { text: "Plowing that ass like a New England corn farmer.", pack: "Green Box" },
  { text: "Eating people.", pack: "Green Box" },
  { text: "An X-Man whose power is that he has sex with dogs and children.", pack: "Green Box" },
  { text: "Gazpacho.", pack: "Green Box" },
  { text: "Slamming a dunk.", pack: "Green Box" },
  { text: "Breastfeeding in public like a radiant earth goddess.", pack: "Green Box" },
  { text: "A black friend.", pack: "Green Box" },
  { text: "Content.", pack: "Green Box" },
  { text: "Tables.", pack: "Green Box" },
  { text: "Facilitating dialogue and deconstructing binaries.", pack: "Green Box" },
  { text: "Every man's ultimate fantasy: a perfectly cylindrical vagina.", pack: "Green Box" },
  { text: "Misogyny.", pack: "Green Box" },
  { text: "One of those \"blow jobs\" I've been hearing so much about.", pack: "Green Box" },
  { text: "The body of a 46-year-old man.", pack: "Green Box" },
  { text: "Jazz.", pack: "Green Box" },
  { text: "You.", pack: "Green Box" },
  { text: "Taking the form of a falcon.", pack: "Green Box" },
  { text: "A dolphin that learns to talk and becomes the Dean of Harvard Law School.", pack: "Green Box" },
  { text: "Quacking like a duck in lieu of a cogent argument.", pack: "Green Box" },
  { text: "Self-identifying as a DJ.", pack: "Green Box" },

  // ── Green Box (white) batch 2 ─────────────────────────────────────────────────
  // Image 1
  { text: "Falling into a pit of waffles.", pack: "Green Box" },
  { text: "Getting blasted in the face by a t-shirt cannon.", pack: "Green Box" },
  { text: "My brother's hot friends.", pack: "Green Box" },
  { text: "Aborting the shit out of a fetus.", pack: "Green Box" },
  { text: "An empowered woman.", pack: "Green Box" },
  { text: "Farting all over my face with your tight little asshole.", pack: "Green Box" },
  { text: "Getting the Dorito crumbs out of my pubes.", pack: "Green Box" },
  { text: "A man in a suit with perfect hair who tells you beautiful lies.", pack: "Green Box" },
  { text: "Comprehensive immigration reform.", pack: "Green Box" },
  { text: "The LGBT community.", pack: "Green Box" },
  { text: "The flaming wreckage of the International Space Station.", pack: "Green Box" },
  { text: "The clown that followed me home from the grocery store.", pack: "Green Box" },
  { text: "Microaggressions.", pack: "Green Box" },
  { text: "Consensual, nonreproductive incest.", pack: "Green Box" },
  { text: "A genetic predisposition for alcoholism.", pack: "Green Box" },
  { text: "Rubbing my bush all over your bald head.", pack: "Green Box" },
  { text: "A finger up the butt.", pack: "Green Box" },
  { text: "Seizing control of the means of production.", pack: "Green Box" },
  { text: "The fear and hatred in men's hearts.", pack: "Green Box" },
  { text: "Awesome pictures of planets and stuff.", pack: "Green Box" },
  { text: "The sweet, forbidden meat of the monkey.", pack: "Green Box" },
  { text: "When the big truck goes \"Toot! Toot!\"", pack: "Green Box" },
  { text: "Getting killed and dragged up a tree by a leopard.", pack: "Green Box" },
  { text: "An older man.", pack: "Green Box" },
  { text: "Getting laid like all the time.", pack: "Green Box" },
  { text: "Eternal screaming madness.", pack: "Green Box" },
  { text: "Film roles for actresses over 40.", pack: "Green Box" },
  { text: "Prematurely ejaculating like a total loser.", pack: "Green Box" },
  { text: "Going around pulling people's tampons out.", pack: "Green Box" },
  { text: "Waking up inside of a tornado.", pack: "Green Box" },
  { text: "A cheerfulness that belies a deep-seated self-loathing.", pack: "Green Box" },
  { text: "Dumpster juice.", pack: "Green Box" },
  { text: "Farting a huge shit out of my pussy.", pack: "Green Box" },
  { text: "Political correctness.", pack: "Green Box" },
  { text: "Albert Einstein but if he had huge muscles and a rhinoceros cock.", pack: "Green Box" },

  // Image 2
  { text: "Tender chunks of all-white-meat chicken.", pack: "Green Box" },
  { text: "Denying the Holocaust.", pack: "Green Box" },
  { text: "A creature made of penises that must constantly arouse itself to survive.", pack: "Green Box" },
  { text: "Forty-five minutes of finger blasting.", pack: "Green Box" },
  { text: "Making out and stuff.", pack: "Green Box" },
  { text: "Salsa Night at Dave's Cantina.", pack: "Green Box" },
  { text: "Chipotle.", pack: "Green Box" },
  { text: "Playing my asshole like a trumpet.", pack: "Green Box" },
  { text: "A tiny fireman who puts out tiny fires.", pack: "Green Box" },
  { text: "Everything.", pack: "Green Box" },
  { text: "Twenty bucks.", pack: "Green Box" },
  { text: "The full-blown marginalization of ugly people.", pack: "Green Box" },
  { text: "Doing a somersault and barfing.", pack: "Green Box" },
  { text: "Working so hard to have muscles and then having them.", pack: "Green Box" },
  { text: "Mommy and daddy fighting all the time.", pack: "Green Box" },
  { text: "Pooping in a leotard and hoping no one notices.", pack: "Green Box" },
  { text: "Getting naked too soon.", pack: "Green Box" },
  { text: "Regurgitating a half-digested sparrow.", pack: "Green Box" },
  { text: "Getting pegged.", pack: "Green Box" },
  { text: "Showing all the boys my pussy.", pack: "Green Box" },
  { text: "Participating.", pack: "Green Box" },
  { text: "Late-stage dementia.", pack: "Green Box" },
  { text: "Defeating a gorilla in single combat.", pack: "Green Box" },
  { text: "How sad it will be when Morgan Freeman dies.", pack: "Green Box" },
  { text: "The hottest MILF in Dallas.", pack: "Green Box" },
  { text: "Some real spicy shrimps.", pack: "Green Box" },
  { text: "Thinking about what eating even is.", pack: "Green Box" },
  { text: "A duffel bag full of lizards.", pack: "Green Box" },
  { text: "Twenty cheerleaders laughing at your tiny penis.", pack: "Green Box" },
  { text: "Happy daddies with happy sandals.", pack: "Green Box" },
  { text: "Having an awesome time drinking and driving.", pack: "Green Box" },
  { text: "Libertarians.", pack: "Green Box" },
  { text: "Whooping your ass at Mario Kart.", pack: "Green Box" },
  { text: "A big, beautiful mouth packed to the brim with sparkling white teeth.", pack: "Green Box" },
  { text: "The Rwandan Genocide.", pack: "Green Box" },

  // Image 3
  { text: "A massive collection of child pornography.", pack: "Green Box" },
  { text: "Systems and policies designed to preserve centuries-old power structures.", pack: "Green Box" },
  { text: "Moon people.", pack: "Green Box" },
  { text: "The ol' penis-in-the-popcorn surprise.", pack: "Green Box" },
  { text: "The lived experience of African Americans.", pack: "Green Box" },
  { text: "Picking up a glass of water and taking a sip and being the president.", pack: "Green Box" },
  { text: "A big ol' plate of fettuccine alfredo.", pack: "Green Box" },
  { text: "Smashing my balls at the moment of climax.", pack: "Green Box" },
  { text: "A slowly encroaching circle of wolves.", pack: "Green Box" },
  { text: "Critical thinking.", pack: "Green Box" },
  { text: "Putting more black people in jail.", pack: "Green Box" },
  { text: "Rock-hard tits and a huge vagina.", pack: "Green Box" },
  { text: "Gregor, my largest son.", pack: "Green Box" },
  { text: "Having a vagina.", pack: "Green Box" },
  { text: "A long business meeting with no obvious purpose.", pack: "Green Box" },
  { text: "The graceful path of an autumn leaf as it falls to its earthen cradle.", pack: "Green Box" },
  { text: "One of them big-city Jew lawyers.", pack: "Green Box" },
  { text: "Informing you that I am a registered sex offender.", pack: "Green Box" },
  { text: "The secret to truly resilient hair.", pack: "Green Box" },
  { text: "Getting eaten out by a dog.", pack: "Green Box" },
  { text: "Brunch.", pack: "Green Box" },
  { text: "China.", pack: "Green Box" },
  { text: "Trees.", pack: "Green Box" },
  { text: "Hating Jews.", pack: "Green Box" },
  { text: "The government.", pack: "Green Box" },
  { text: "Blossoming into a beautiful young woman.", pack: "Green Box" },
  { text: "Mental illness.", pack: "Green Box" },
  { text: "Having sex with your mom.", pack: "Green Box" },
  { text: "Going to bed at a reasonable hour.", pack: "Green Box" },
  { text: "A woman's perspective.", pack: "Green Box" },
  { text: "Restoring Germany to its former glory.", pack: "Green Box" },
  { text: "Menopause.", pack: "Green Box" },
  { text: "Anal.", pack: "Green Box" },
  { text: "Munchin' puss.", pack: "Green Box" },
  { text: "Homework.", pack: "Green Box" },

  // Image 4
  { text: "The feeling of going to McDonald's as a 6-year-old.", pack: "Green Box" },
  { text: "Feeling the emotion of anger.", pack: "Green Box" },
  { text: "Guns.", pack: "Green Box" },
  { text: "Getting this party started!", pack: "Green Box" },
  { text: "Showering praise upon the Sultan's hideous daughters.", pack: "Green Box" },
  { text: "Feminism.", pack: "Green Box" },
  { text: "Huge big balls full of jizz.", pack: "Green Box" },
  { text: "Fucking me good and taking me to Red Lobster®.", pack: "Green Box" },
  { text: "Big, smart money boys tap-tapping on their keyboards.", pack: "Green Box" },
  { text: "Overthrowing the democratically-elected government of Chile.", pack: "Green Box" },
  { text: "Crazy anal orgasms.", pack: "Green Box" },
  { text: "Getting trapped in a conversation about Ayn Rand.", pack: "Green Box" },
  { text: "A strong horse and enough rations for thirty days.", pack: "Green Box" },
  { text: "The amount of baby carrots I can fit up my ass.", pack: "Green Box" },
  { text: "Assassinating the president.", pack: "Green Box" },
  { text: "Founding a major world religion.", pack: "Green Box" },
  { text: "Starting a shitty podcast.", pack: "Green Box" },
  { text: "Getting aborted.", pack: "Green Box" },
  { text: "Antidepressants.", pack: "Green Box" },
  { text: "Dis bitch.", pack: "Green Box" },
  { text: "An incurable homosexual.", pack: "Green Box" },
  { text: "That chicken from Popeyes®.", pack: "Green Box" },
  { text: "A burrito that's just sour cream.", pack: "Green Box" },
  { text: "10 football players with erections barrelling towards you at full speed.", pack: "Green Box" },
  { text: "A hug.", pack: "Green Box" },
  { text: "Being sexually attracted to children.", pack: "Green Box" },
  { text: "Dominating a man by peeing on his eldest son.", pack: "Green Box" },
  { text: "A cold and indifferent universe.", pack: "Green Box" },
  { text: "Whomsoever let the dogs out.", pack: "Green Box" },
  { text: "A man with the head of a goat and the body of a goat.", pack: "Green Box" },
  { text: "10,000 shrieking teenage girls.", pack: "Green Box" },
  { text: "Sucking each other's penises for hours on end.", pack: "Green Box" },
  { text: "Doritos and a Fruit Roll-Up.", pack: "Green Box" },
  { text: "Water.", pack: "Green Box" },
  { text: "Art.", pack: "Green Box" },

  // ── Green Box (white) batch 3 ─────────────────────────────────────────────────
  { text: "Having sex with a beautiful person.", pack: "Green Box" },
  { text: "Two shitty kids and a garbage husband.", pack: "Green Box" },
  { text: "Ejaculating at the apex of a cartwheel.", pack: "Green Box" },
  { text: "Crushing the patriarchy.", pack: "Green Box" },
  { text: "A weird guy who says weird stuff and weirds me out.", pack: "Green Box" },
  { text: "Meatloaf, the man.", pack: "Green Box" },
  { text: "Hot lettuce.", pack: "Green Box" },
  { text: "Raising three kids on minimum wage.", pack: "Green Box" },
  { text: "A terrified fat child who won't come out of the bushes.", pack: "Green Box" },
  { text: "My dog dying.", pack: "Green Box" },
  { text: "It being too late to stop having sex with a horse.", pack: "Green Box" },
  { text: "Grunting for ten minutes and then peeing sand.", pack: "Green Box" },
  { text: "Meatloaf, the food.", pack: "Green Box" },
  { text: "Straight blazin' 24/7.", pack: "Green Box" },
  { text: "The mysterious fog rolling into town.", pack: "Green Box" },
  { text: "Mixing M&Ms and Skittles like some kind of psychopath.", pack: "Green Box" },
  { text: "Chris Hemsworth.", pack: "Green Box" },
  { text: "Child labor.", pack: "Green Box" },
  { text: "How strange it is to be anything at all.", pack: "Green Box" },
  { text: "Scissoring, if that's a thing.", pack: "Green Box" },
  { text: "Creamy slices of real, California avocado.", pack: "Green Box" },
  { text: "Who really did 9/11.", pack: "Green Box" },
  { text: "Rolling so hard.", pack: "Green Box" },
  { text: "How good lead paint taste.", pack: "Green Box" },
  { text: "All the people I've killed.", pack: "Green Box" },
  { text: "Holding the proper political beliefs of my time to attract a mate.", pack: "Green Box" },
  { text: "Some of that good dick.", pack: "Green Box" },
  { text: "Objectifying women.", pack: "Green Box" },
  { text: "The bond between a woman and her horse.", pack: "Green Box" },
  { text: "A medium horchata.", pack: "Green Box" },
  { text: "How great my ass looks in these jeans.", pack: "Green Box" },
  { text: "Dropping dead in a Sbarro's bathroom and not being found for 72 hours.", pack: "Green Box" },
  { text: "Quinoa.", pack: "Green Box" },
  { text: "Onions.", pack: "Green Box" },
  { text: "Three hours of nonstop penetration.", pack: "Green Box" },

  // ── Green Box (white) batch 4 ─────────────────────────────────────────────────
  { text: "Discovering that what I really want in life is to kill people and have sex with their corpses.", pack: "Green Box" },
  { text: "A negative body image that is totally justified.", pack: "Green Box" },
  { text: "Two beautiful pig sisters.", pack: "Green Box" },
  { text: "Daddy going away forever.", pack: "Green Box" },
  { text: "My huge penis and substantial fortune.", pack: "Green Box" },
  { text: "Finding a nice elevator to poop in.", pack: "Green Box" },
  { text: "Our baby.", pack: "Green Box" },
  { text: "Sudden and unwanted slam poetry.", pack: "Green Box" },
  { text: "Condoleezza Rice.", pack: "Green Box" },
  { text: "Catching a live salmon in your mouth.", pack: "Green Box" },
  { text: "An old dog dragging its anus across the floor.", pack: "Green Box" },
  { text: "Reaching an age where barbecue chips are better than sex.", pack: "Green Box" },
  { text: "The full force of the American military.", pack: "Green Box" },
  { text: "Turning 32.", pack: "Green Box" },
  { text: "A woman's right to choose.", pack: "Green Box" },
  { text: "Watching a hot person eat.", pack: "Green Box" },
  { text: "The best, deepest quotes from The Dark Knight.", pack: "Green Box" },
  { text: "ISIS.", pack: "Green Box" },
  { text: "Gay thoughts.", pack: "Green Box" },
  { text: "Being turned into sausages.", pack: "Green Box" },
  { text: "Beyoncé.", pack: "Green Box" },
  { text: "Fucking my therapist.", pack: "Green Box" },
  { text: "Pretending to be one of the guys but actually being the spider god.", pack: "Green Box" },
  { text: "Becoming the President of the United States.", pack: "Green Box" },
  { text: "Eating too many Cinnabons and then vomiting and then eating the vomit.", pack: "Green Box" },
  { text: "Exploring each other's buttholes.", pack: "Green Box" },
  { text: "A creepy child singing a nursery rhyme.", pack: "Green Box" },
  { text: "Pooping in the potty.", pack: "Green Box" },
  { text: "Period poops.", pack: "Green Box" },
  { text: "Getting high with mom.", pack: "Green Box" },
];
