const WHITE_CARDS = [
  // ── Photo 1 ──────────────────────────────────────────────────────────────────
  "The card Neil Gaiman wrote: \"Three elves at a time.\"",
  "A weed elemental who gets everyone high.",
  "Loading from a previous save.",
  "The collective wail of every Magic player suddenly realizing that they've spent hundreds of dollars on pieces of cardboard.",
  "Ser Jorah Mormont's cerulean-blue balls.",
  "True love's kiss.",
  "Going on an epic adventure and learning a valuable lesson about friendship.",
  "Kneeing a wizard in the balls.",
  "Bathing naked in a moonlit grove.",
  "A ghoul.",
  "Handcuffing a wizard to a radiator and dousing him with kerosene.",
  "Offering sexual favors for an ore and a sheep.",
  "Getting bitten by a radioactive spider and then battling leukemia for 30 years.",
  "Freaky, pan-dimensional sex with a demigod.",
  "Separate drinking fountains for dark elves.",
  "A homemade, cum-stained Star Trek uniform.",
  "Make-believe stories for autistic white men.",
  "Shitting in a wizard's spell book and jizzing in his hat.",
  "Endless ninjas.",
  "How hot Orlando Bloom was in Lord of the Rings.",

  // ── Photo 2 ──────────────────────────────────────────────────────────────────
  "Getting bitch slapped by Dhalsim.",
  "A mysterious, floating orb.",
  "A fully-dressed female videogame character.",
  "Gender equality.",
  "Stuffing my balls into a Sega Genesis and pressing the power button.",
  "Running out of stamina.",
  "Yoshi's huge egg-laying cloaca.",
  "The Cock Ring of Alacrity.",
  "Charging up all the way.",
  "The depression that ensues after catching 'em all.",
  "Accidentally conjuring a legless horse that can't stop ejaculating.",
  "Forgetting to eat, and consequently dying.",
  "A grumpy old Harrison Ford who'd rather be doing anything else.",
  "Sharpening a foam broadsword on a foam whetstone.",
  "Eating a pizza that's lying in the street to gain health.",
  "Eternal darkness.",
  "Reading The Hobbit under the covers while mom and dad scream at each other downstairs.",
  "Hodor.",
  "Shooting a wizard with a gun.",
  "Taking 2d6 emotional damage.",
  "A CGI dragon.",
  "The all-seeing Eye of Sauron.",
  "Achieving 500 actions per minute.",
  "A magical kingdom with dragons and elves and no black people.",

  // ── Photo 3 ──────────────────────────────────────────────────────────────────
  "Beep beep boop beep boop.",
  "Dinosaurs who wear armor and you ride them and they kick ass.",
  "KHAAAAAAAAAAN!",
  "Tapping Serra Angel.",
  "How great of a movie Men in Black was.",
  "A dwarf who won't leave you alone until you compare penis sizes.",
  "A Hitachi Magic Wand.",
  "A gay sorcerer who turns everyone gay.",
  "Nine seasons of sexual tension with David Duchovny.",
  "Masturbating Yoda's leathery turtle-penis.",
  "A misty room full of glistening egg sacs.",
  "Frantically writing equations on a chalkboard.",
  "Darmok and Jalad at Tanagra.",
  "A protagonist with no qualities.",
  "Going too far with science and bad things happening.",
  "Vulcan sex-madness.",
  "That girl from the Hungry Games.",
  "Cheerful blowjob robots.",
  "Three boobs.",
  "Funkified aliens from the planet Groovius.",
  "The ending of Lost.",
  "Cosmic bowling.",
  "An alternate history where Hitler was gay but he still killed all those people.",
  "The dystopia we're living in right now.",
  "A planet-devouring space worm named Rachel.",
  "Trimming the poop out of Chewbacca's butt hair.",
  "A hazmat suit full of farts.",
  "Laying thousands of eggs in a man's colon.",
];
